// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/13/2025, 6:05:10 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/emg/RiderProjects/Blog/FrontEnd/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/emg/RiderProjects/Blog/FrontEnd/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/emg/RiderProjects/Blog/FrontEnd/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/emg/RiderProjects/Blog/FrontEnd/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/emg/RiderProjects/Blog/FrontEnd/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/emg/RiderProjects/Blog/FrontEnd/plugins/**/*.{js,ts,mjs}","/home/emg/RiderProjects/Blog/FrontEnd/composables/**/*.{js,ts,mjs}","/home/emg/RiderProjects/Blog/FrontEnd/utils/**/*.{js,ts,mjs}","/home/emg/RiderProjects/Blog/FrontEnd/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/emg/RiderProjects/Blog/FrontEnd/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/emg/RiderProjects/Blog/FrontEnd/app.config.{js,ts,mjs}","/home/emg/RiderProjects/Blog/FrontEnd/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;