// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/29/2025, 12:40:31 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/Blog/FrontEnd/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Blog/FrontEnd/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Blog/FrontEnd/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Blog/FrontEnd/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Blog/FrontEnd/plugins/**/*.{js,ts,mjs}","D:/Blog/FrontEnd/composables/**/*.{js,ts,mjs}","D:/Blog/FrontEnd/utils/**/*.{js,ts,mjs}","D:/Blog/FrontEnd/pages/admin/categories/index.vue","D:/Blog/FrontEnd/pages/admin/index.vue","D:/Blog/FrontEnd/pages/admin/posts/create.vue","D:/Blog/FrontEnd/pages/admin/posts/edit.vue","D:/Blog/FrontEnd/pages/admin/posts/index.vue","D:/Blog/FrontEnd/pages/admin/tags/index.vue","D:/Blog/FrontEnd/pages/auth/login.vue","D:/Blog/FrontEnd/pages/categories/create.vue","D:/Blog/FrontEnd/pages/categories/Edit.vue","D:/Blog/FrontEnd/pages/categories/index.vue","D:/Blog/FrontEnd/pages/index.vue","D:/Blog/FrontEnd/pages/inspire.vue","D:/Blog/FrontEnd/pages/login.vue","D:/Blog/FrontEnd/pages/posts/[slug].vue","D:/Blog/FrontEnd/pages/posts/index.vue","D:/Blog/FrontEnd/pages/tags/[slug].vue","D:/Blog/FrontEnd/pages/tags/create.vue","D:/Blog/FrontEnd/pages/tags/Edit.vue","D:/Blog/FrontEnd/pages/tags/index.vue","D:/Blog/FrontEnd/pages/tags/list.vue","D:/Blog/FrontEnd/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Blog/FrontEnd/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Blog/FrontEnd/app.config.{js,ts,mjs}","D:/Blog/FrontEnd/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;