// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/19/2025, 2:25:08 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/Blog/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Blog/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Blog/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Blog/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Blog/frontend/plugins/**/*.{js,ts,mjs}","D:/Blog/frontend/composables/**/*.{js,ts,mjs}","D:/Blog/frontend/utils/**/*.{js,ts,mjs}","D:/Blog/frontend/pages/admin/categories/index.vue","D:/Blog/frontend/pages/admin/index.vue","D:/Blog/frontend/pages/admin/posts/create.vue","D:/Blog/frontend/pages/admin/posts/edit.vue","D:/Blog/frontend/pages/admin/posts/index.vue","D:/Blog/frontend/pages/admin/tags/index.vue","D:/Blog/frontend/pages/auth/login.vue","D:/Blog/frontend/pages/categories/create.vue","D:/Blog/frontend/pages/categories/Edit.vue","D:/Blog/frontend/pages/categories/index.vue","D:/Blog/frontend/pages/index.vue","D:/Blog/frontend/pages/inspire.vue","D:/Blog/frontend/pages/login.vue","D:/Blog/frontend/pages/posts/[slug].vue","D:/Blog/frontend/pages/tags/[slug].vue","D:/Blog/frontend/pages/tags/create.vue","D:/Blog/frontend/pages/tags/Edit.vue","D:/Blog/frontend/pages/tags/index.vue","D:/Blog/frontend/pages/tags/list.vue","D:/Blog/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Blog/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Blog/frontend/app.config.{js,ts,mjs}","D:/Blog/frontend/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;